# Use root/example as user/password credentials
version: '3.8'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root

    ports:
      - 3306:3306
